/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Aluno;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Model.Aluno;
import View.Aluno.LoginAluno;

/**
 *
 * @author Aluno
 */
public class TelaAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAluno
     */
    public TelaAluno() {
        initComponents();
    }

    private Aluno alunoLogado;
    
    // construtor que recebe o aluno logado
    public TelaAluno(Aluno alunoLogado) {
        this.alunoLogado = alunoLogado;  // inicializa o final aqui

        initComponents();

        if (this.alunoLogado != null) {
            cxNome.setText(this.alunoLogado.getNome());
            carregarNomeInstrutor();
        }
    }
    
    private void carregarNomeInstrutor() {
        String sql = """
            SELECT i.nome AS instrutor_nome
            FROM aluno a
            JOIN instrutor i ON a.instrutor_id = i.id_instrutor
            WHERE a.id_aluno = ?
        """;

        try (Connection con = Control.BD.ConexaoBD.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, alunoLogado.getIdAluno());

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String nomeInstrutor = rs.getString("instrutor_nome");
                    cxNomeInstrutor.setText(nomeInstrutor != null ? nomeInstrutor : "");
                } else {
                    cxNomeInstrutor.setText("Sem instrutor vinculado");
                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao carregar nome do instrutor:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            cxNomeInstrutor.setText("");
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        labelInstrutor = new javax.swing.JLabel();
        cxNomeInstrutor = new javax.swing.JTextField();
        menuAluno = new javax.swing.JMenuBar();
        menuFichas = new javax.swing.JMenu();
        itemVerFicha = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuAvaliacoes = new javax.swing.JMenu();
        itemVerAvaliacoes = new javax.swing.JMenuItem();
        div2 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Nome do aluno:");

        cxNome.setEditable(false);
        cxNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelInstrutor.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelInstrutor.setText("Nome do instrutor:");

        cxNomeInstrutor.setEditable(false);
        cxNomeInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeInstrutorActionPerformed(evt);
            }
        });

        menuFichas.setText("Ver ficha");
        menuFichas.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemVerFicha.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemVerFicha.setText("Ver ficha");
        itemVerFicha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerFichaActionPerformed(evt);
            }
        });
        menuFichas.add(itemVerFicha);

        menuAluno.add(menuFichas);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAluno.add(div1);

        menuAvaliacoes.setText("Ver avaliações");
        menuAvaliacoes.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemVerAvaliacoes.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemVerAvaliacoes.setText("Ver avaliações");
        itemVerAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerAvaliacoesActionPerformed(evt);
            }
        });
        menuAvaliacoes.add(itemVerAvaliacoes);

        menuAluno.add(menuAvaliacoes);

        div2.setText("|");
        div2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAluno.add(div2);

        menuSair.setBackground(new java.awt.Color(255, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 0, 0));
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuAluno.add(menuSair);

        setJMenuBar(menuAluno);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelInstrutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNomeInstrutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelInstrutor)
                    .addComponent(cxNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(168, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxNomeInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeInstrutorActionPerformed

    private void itemVerFichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerFichaActionPerformed
        VerTreinoAluno tela = new VerTreinoAluno(alunoLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemVerFichaActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // cria um objeto da tela
        LoginAluno telaLogin = new LoginAluno();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual 
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemVerAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerAvaliacoesActionPerformed
        VerAvaliacaoAluno tela = new VerAvaliacaoAluno(alunoLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemVerAvaliacoesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNomeInstrutor;
    private javax.swing.JMenu div1;
    private javax.swing.JMenu div2;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemVerAvaliacoes;
    private javax.swing.JMenuItem itemVerFicha;
    private javax.swing.JLabel labelInstrutor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JMenuBar menuAluno;
    private javax.swing.JMenu menuAvaliacoes;
    private javax.swing.JMenu menuFichas;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
