/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Aluno;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Model.Aluno;
import View.Aluno.TelaAluno;

/**
 *
 * @author Aluno
 */
public class VerAvaliacaoAluno extends javax.swing.JFrame {

    private Aluno alunoLogado;

    public VerAvaliacaoAluno() {
        initComponents();
    }

    public VerAvaliacaoAluno(Aluno alunoLogado) {
        this.alunoLogado = alunoLogado;
        initComponents();

        if (this.alunoLogado != null) {
            cxNome.setText(this.alunoLogado.getNome());
        }
        carregarUltimaAvaliacao();
    }

    private void limparCampos() {
        cxData.setText("");
        cxCoef.setText("");
        cxBF.setText("");
        cxPeso.setText("");
    }

    private void carregarUltimaAvaliacao() {
        if (alunoLogado == null) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Não foi possível identificar o aluno logado.",
                "Aviso",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
            limparCampos();
            return;
        }

        String sql = """
            SELECT a.data_avaliacao,
                   a.coef_forca,
                   a.bf,
                   a.peso,
                   i.nome AS instrutor_nome
            FROM avaliacao a
            JOIN aluno al ON a.aluno_id = al.id_aluno
            LEFT JOIN instrutor i ON al.instrutor_id = i.id_instrutor
            WHERE a.aluno_id = ?
            ORDER BY a.data_avaliacao DESC
            LIMIT 1
        """;

        try (Connection con = Control.BD.ConexaoBD.conectar();
             PreparedStatement ps = con.prepareStatement(sql)) {

            ps.setInt(1, alunoLogado.getIdAluno());

            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    var ts   = rs.getTimestamp("data_avaliacao");
                    String dataStr = ts != null ? ts.toLocalDateTime().toString().substring(0, 10) : "";

                    float coef = rs.getFloat("coef_forca");
                    float bf   = rs.getFloat("bf");
                    float peso = rs.getFloat("peso");
                    String instrutorNome = rs.getString("instrutor_nome");

                    cxData.setText(dataStr);
                    cxCoef.setText(String.valueOf(coef));
                    cxBF.setText(String.valueOf(bf));
                    cxPeso.setText(String.valueOf(peso));

                }
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao carregar sua avaliação:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            limparCampos();
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        labelData = new javax.swing.JLabel();
        cxData = new javax.swing.JTextField();
        labelCoef = new javax.swing.JLabel();
        cxCoef = new javax.swing.JTextField();
        labelBF = new javax.swing.JLabel();
        cxBF = new javax.swing.JTextField();
        labelPeso = new javax.swing.JLabel();
        cxPeso = new javax.swing.JTextField();
        menuAvaliacao = new javax.swing.JMenuBar();
        menuAvaliacoesAntigas = new javax.swing.JMenu();
        itemVerAvaliacoesAntigas = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuVoltar = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Nome do aluno:");

        cxNome.setEditable(false);
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelData.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelData.setText("Data:");

        cxData.setEditable(false);
        cxData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDataActionPerformed(evt);
            }
        });

        labelCoef.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelCoef.setText("Coeficiente de força:");

        cxCoef.setEditable(false);
        cxCoef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCoefActionPerformed(evt);
            }
        });

        labelBF.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelBF.setText("% de gordura corporal:");

        cxBF.setEditable(false);
        cxBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxBFActionPerformed(evt);
            }
        });

        labelPeso.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelPeso.setText("Peso:");

        cxPeso.setEditable(false);
        cxPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPesoActionPerformed(evt);
            }
        });

        menuAvaliacoesAntigas.setText("Ver avaliações antigas");
        menuAvaliacoesAntigas.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N

        itemVerAvaliacoesAntigas.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemVerAvaliacoesAntigas.setText("Ver avaliações antigas");
        itemVerAvaliacoesAntigas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerAvaliacoesAntigasActionPerformed(evt);
            }
        });
        menuAvaliacoesAntigas.add(itemVerAvaliacoesAntigas);

        menuAvaliacao.add(menuAvaliacoesAntigas);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAvaliacao.add(div1);

        menuVoltar.setBackground(new java.awt.Color(255, 0, 0));
        menuVoltar.setForeground(new java.awt.Color(255, 0, 0));
        menuVoltar.setText("Voltar");
        menuVoltar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setBackground(new java.awt.Color(51, 255, 51));
        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Voltar");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuVoltar.add(itemSair);

        menuAvaliacao.add(menuVoltar);

        setJMenuBar(menuAvaliacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelPeso)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cxPeso))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelBF)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cxBF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelCoef)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cxCoef))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelData)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cxData))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelData)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoef)
                    .addComponent(cxCoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBF)
                    .addComponent(cxBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPeso)
                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataActionPerformed

    private void cxCoefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCoefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCoefActionPerformed

    private void cxBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxBFActionPerformed

    private void cxPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPesoActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        TelaAluno tela = new TelaAluno(alunoLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemVerAvaliacoesAntigasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerAvaliacoesAntigasActionPerformed
        HistoricoAvaliacoesAluno tela = new HistoricoAvaliacoesAluno(alunoLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemVerAvaliacoesAntigasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAvaliacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAvaliacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAvaliacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAvaliacaoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAvaliacaoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxBF;
    private javax.swing.JTextField cxCoef;
    private javax.swing.JTextField cxData;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JMenu div1;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemVerAvaliacoesAntigas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel labelBF;
    private javax.swing.JLabel labelCoef;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPeso;
    private javax.swing.JMenuBar menuAvaliacao;
    private javax.swing.JMenu menuAvaliacoesAntigas;
    private javax.swing.JMenu menuVoltar;
    // End of variables declaration//GEN-END:variables
}
