/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Aluno;
import Control.BD.ConexaoBD;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

import Model.Aluno;
import View.Aluno.TelaAluno;

/**
 *
 * @author Aluno
 */
public class VerTreinoAluno extends javax.swing.JFrame {

    private Aluno alunoLogado;

    public VerTreinoAluno() {
        initComponents();
    }

    public VerTreinoAluno(Aluno alunoLogado) {
        this.alunoLogado = alunoLogado;
        initComponents();

        if (this.alunoLogado != null) {
            cxNome.setText(this.alunoLogado.getNome()); // por exemplo
        }
        carregarTreinoAluno();
    }

    
    private void carregarTreinoAluno() {
        if (alunoLogado == null) return;

        Integer treinoId    = alunoLogado.getTreinoId();
        Integer instrutorId = alunoLogado.getInstrutorId();

        Connection conn = null;
        Statement st    = null;
        ResultSet rs    = null;

        try {
            conn = ConexaoBD.conectar();
            st   = conn.createStatement();

            // 1) Carrega nome do instrutor (se tiver instrutor vinculado)
            if (instrutorId != null) {
                String sqlInstr = "SELECT nome FROM instrutor WHERE id_instrutor = " + instrutorId;
                rs = st.executeQuery(sqlInstr);
                if (rs.next()) {
                    cxNomeInstrutor.setText(rs.getString("nome"));
                }
                rs.close();
                rs = null;
            }

            // 2) Carrega exercícios do treino (se tiver treino vinculado)
            if (treinoId == null) {
                return; // não tem treino ainda
            }

            String sqlEx = "SELECT nome, peso, repeticoes " +
                           "FROM exercicio " +
                           "WHERE treino_id = " + treinoId;

            rs = st.executeQuery(sqlEx);

            DefaultTableModel model = (DefaultTableModel) tabelaExercicios.getModel();
            model.setRowCount(0); // limpa linhas atuais

            while (rs.next()) {
                String nome = rs.getString("nome");
                String peso = rs.getString("peso");
                String reps = rs.getString("repeticoes");

                // colunas: "Nome do exercício", "Peso", "Séries", "Repetições"
                model.addRow(new Object[] {
                    nome,
                    peso,
                    reps
                });
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao carregar treino do aluno:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        } finally {
            try {
                if (rs   != null) rs.close();
                if (st   != null) st.close();
                if (conn != null) conn.close();
            } catch (Exception ex) {
                // ignora erro de fechamento
            }
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        labelInstrutor = new javax.swing.JLabel();
        cxNomeInstrutor = new javax.swing.JTextField();
        scrollExercicios = new javax.swing.JScrollPane();
        tabelaExercicios = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Nome do aluno:");

        cxNome.setEditable(false);
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelInstrutor.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelInstrutor.setText("Nome do instrutor:");

        cxNomeInstrutor.setEditable(false);
        cxNomeInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeInstrutorActionPerformed(evt);
            }
        });

        tabelaExercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome do exercício", "Peso", "Repetições"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollExercicios.setViewportView(tabelaExercicios);
        if (tabelaExercicios.getColumnModel().getColumnCount() > 0) {
            tabelaExercicios.getColumnModel().getColumn(0).setResizable(false);
            tabelaExercicios.getColumnModel().getColumn(1).setResizable(false);
            tabelaExercicios.getColumnModel().getColumn(2).setResizable(false);
        }

        btnVoltar.setBackground(new java.awt.Color(0, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Swis721 Blk BT", 0, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollExercicios)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(labelInstrutor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInstrutor)
                    .addComponent(cxNomeInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollExercicios, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxNomeInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeInstrutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeInstrutorActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaAluno tela = new TelaAluno(alunoLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerTreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerTreinoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNomeInstrutor;
    private javax.swing.JLabel labelInstrutor;
    private javax.swing.JLabel labelNome;
    private javax.swing.JScrollPane scrollExercicios;
    private javax.swing.JTable tabelaExercicios;
    // End of variables declaration//GEN-END:variables
}
