/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import View.Instrutor.LoginInstrutor;
import View.Admin.LoginAdmin;
import View.Aluno.LoginAluno;

/**
 *
 * @author Aluno
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        btnAluno = new javax.swing.JButton();
        btnInstrutor = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelLogin.setText("Tela de login");

        btnAluno.setBackground(new java.awt.Color(0, 0, 0));
        btnAluno.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        btnAluno.setForeground(new java.awt.Color(255, 0, 0));
        btnAluno.setText("Login aluno");
        btnAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunoActionPerformed(evt);
            }
        });

        btnInstrutor.setBackground(new java.awt.Color(0, 0, 0));
        btnInstrutor.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        btnInstrutor.setForeground(new java.awt.Color(255, 0, 0));
        btnInstrutor.setText("Login instrutor");
        btnInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstrutorActionPerformed(evt);
            }
        });

        btnAdmin.setBackground(new java.awt.Color(0, 0, 0));
        btnAdmin.setFont(new java.awt.Font("Swis721 Cn BT", 1, 18)); // NOI18N
        btnAdmin.setForeground(new java.awt.Color(255, 0, 0));
        btnAdmin.setText("Login admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInstrutor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelLogin)
                        .addGap(24, 24, 24)))
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnAluno))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(btnAdmin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogin)
                .addGap(18, 18, 18)
                .addComponent(btnAluno)
                .addGap(18, 18, 18)
                .addComponent(btnInstrutor)
                .addGap(18, 18, 18)
                .addComponent(btnAdmin)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunoActionPerformed
        // cria um objeto da tela
        LoginAluno telaLogin = new LoginAluno();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual 
        this.dispose();
    }//GEN-LAST:event_btnAlunoActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // cria um objeto da tela
        LoginAdmin telaLogin = new LoginAdmin();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual 
        this.dispose();
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstrutorActionPerformed
        // cria um objeto da tela
        LoginInstrutor telaLogin = new LoginInstrutor();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual 
        this.dispose();
    }//GEN-LAST:event_btnInstrutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAluno;
    private javax.swing.JButton btnInstrutor;
    private javax.swing.JLabel labelLogin;
    // End of variables declaration//GEN-END:variables
}
