/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Instrutor;
import Model.Aluno;
import Model.Instrutor;
import View.Aluno.HistoricoAvaliacoesAluno;
/**
 *
 * @author T-GAMER
 */
public class AlunosInstrutor extends javax.swing.JFrame {

   
    private Instrutor instrutorLogado;
    private Aluno alunoSelecionado;
    
    public AlunosInstrutor() {
        initComponents();
    }
    
    public AlunosInstrutor(Instrutor instrutorLogado, Aluno alunoSelecionado) {
        this.instrutorLogado = instrutorLogado;
        this.alunoSelecionado = alunoSelecionado;
        initComponents();

        if (alunoSelecionado != null) {
            // exemplo: mostrar o nome do aluno em algum label
            cxNome.setText(alunoSelecionado.getNome()); 
            setTitle("Aluno " + alunoSelecionado.getNome() + " - Instrutor " + instrutorLogado.getNome());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        btnAvaliacoes = new javax.swing.JButton();
        btnVerTreino = new javax.swing.JButton();
        menuInstrutor = new javax.swing.JMenuBar();
        menuTreino = new javax.swing.JMenu();
        itemMontarTreino = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuAvaliacao = new javax.swing.JMenu();
        itemFazerAvaliação = new javax.swing.JMenuItem();
        div2 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Nome do aluno:");

        cxNome.setEditable(false);
        cxNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        btnAvaliacoes.setBackground(new java.awt.Color(102, 102, 102));
        btnAvaliacoes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAvaliacoes.setForeground(new java.awt.Color(255, 255, 255));
        btnAvaliacoes.setText("Ver avaliações");
        btnAvaliacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvaliacoesActionPerformed(evt);
            }
        });

        btnVerTreino.setBackground(new java.awt.Color(102, 102, 102));
        btnVerTreino.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerTreino.setForeground(new java.awt.Color(255, 255, 255));
        btnVerTreino.setText("Ver treino atual");
        btnVerTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerTreinoActionPerformed(evt);
            }
        });

        menuTreino.setText("Montar treino");
        menuTreino.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemMontarTreino.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemMontarTreino.setText("Montar treino");
        itemMontarTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMontarTreinoActionPerformed(evt);
            }
        });
        menuTreino.add(itemMontarTreino);

        menuInstrutor.add(menuTreino);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuInstrutor.add(div1);

        menuAvaliacao.setText("Fazer avaliação");
        menuAvaliacao.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemFazerAvaliação.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemFazerAvaliação.setText("Fazer avaliação");
        itemFazerAvaliação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFazerAvaliaçãoActionPerformed(evt);
            }
        });
        menuAvaliacao.add(itemFazerAvaliação);

        menuInstrutor.add(menuAvaliacao);

        div2.setText("|");
        div2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuInstrutor.add(div2);

        menuSair.setBackground(new java.awt.Color(255, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 0, 0));
        menuSair.setText("Voltar");
        menuSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Voltar");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuInstrutor.add(menuSair);

        setJMenuBar(menuInstrutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAvaliacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVerTreino)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAvaliacoes)
                    .addComponent(btnVerTreino))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void itemMontarTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMontarTreinoActionPerformed
        MontarTreinoInstrutor tela = new MontarTreinoInstrutor(instrutorLogado, alunoSelecionado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemMontarTreinoActionPerformed

    private void itemFazerAvaliaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFazerAvaliaçãoActionPerformed
        FazerAvaliacaoInstrutor tela = new FazerAvaliacaoInstrutor(instrutorLogado, alunoSelecionado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemFazerAvaliaçãoActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        VerAlunosInstrutor tela = new VerAlunosInstrutor(instrutorLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void btnAvaliacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvaliacoesActionPerformed
        HistoricoAvaliacoesInstrutor tela = new HistoricoAvaliacoesInstrutor(instrutorLogado, alunoSelecionado);
        tela.setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_btnAvaliacoesActionPerformed

    private void btnVerTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerTreinoActionPerformed
        VerTreinoAlunoInstrutor tela = new VerTreinoAlunoInstrutor(instrutorLogado, alunoSelecionado);
        tela.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnVerTreinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlunosInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvaliacoes;
    private javax.swing.JButton btnVerTreino;
    private javax.swing.JTextField cxNome;
    private javax.swing.JMenu div1;
    private javax.swing.JMenu div2;
    private javax.swing.JMenuItem itemFazerAvaliação;
    private javax.swing.JMenuItem itemMontarTreino;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JMenu menuAvaliacao;
    private javax.swing.JMenuBar menuInstrutor;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenu menuTreino;
    // End of variables declaration//GEN-END:variables
}
