/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Instrutor;

import Model.Aluno;
import Model.Instrutor;
import View.Instrutor.AlunosInstrutor;

/**
 *
 * @author T-GAMER
 */
public class FazerAvaliacaoInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form FazerAvaliacaoInstrutor
     */
    public FazerAvaliacaoInstrutor() {
        initComponents();
    }

    private Instrutor instrutorLogado;
    private Aluno alunoSelecionado;

    public FazerAvaliacaoInstrutor(Instrutor instrutorLogado, Aluno alunoSelecionado) {
        this.instrutorLogado = instrutorLogado;
        this.alunoSelecionado = alunoSelecionado;
        initComponents();
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        labelExercicio1 = new javax.swing.JLabel();
        cxPeso = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        cxCoef = new javax.swing.JTextField();
        labelExercicio2 = new javax.swing.JLabel();
        cxBF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalvar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 255, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 0, 0));
        btnSair.setText("Voltar");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        labelExercicio1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio1.setText("Peso:");

        cxPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPesoActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Coef. de força:");

        cxCoef.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxCoef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxCoefActionPerformed(evt);
            }
        });

        labelExercicio2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio2.setText("BF:");

        cxBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxBFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelExercicio2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxBF))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelExercicio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxPeso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxCoef, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxCoef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio1)
                    .addComponent(cxPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio2)
                    .addComponent(cxBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPesoActionPerformed

    private void cxCoefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCoefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCoefActionPerformed

    private void cxBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxBFActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        AlunosInstrutor tela = new AlunosInstrutor(instrutorLogado, alunoSelecionado);
        
        tela.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // cria tabela (caso ainda não exista)
            Control.BD.AvaliacaoDAO dao = new Control.BD.AvaliacaoDAO();
            dao.criarTabela();

            // cria objeto da avaliação
            Model.Avaliacao av = new Model.Avaliacao(
                alunoSelecionado,
                Float.parseFloat(cxCoef.getText()),
                Float.parseFloat(cxPeso.getText()),
                Float.parseFloat(cxBF.getText())
            );

            // salva no banco
            dao.salvar(av);

            javax.swing.JOptionPane.showMessageDialog(this,
                "Avaliação salva com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Erro ao salvar avaliação:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FazerAvaliacaoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FazerAvaliacaoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FazerAvaliacaoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FazerAvaliacaoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FazerAvaliacaoInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cxBF;
    private javax.swing.JTextField cxCoef;
    private javax.swing.JTextField cxPeso;
    private javax.swing.JLabel labelExercicio1;
    private javax.swing.JLabel labelExercicio2;
    private javax.swing.JLabel labelNome;
    // End of variables declaration//GEN-END:variables
}
