/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Instrutor;

import Control.IA.GeradorTreinoIA;
import Control.IA.OpenRouterClient;
import Control.TreinoParametrosDialog;
import Model.Aluno;
import Model.Instrutor;


/**
 *
 * @author T-GAMER
 */
public class MontarTreinoInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form MontarTreinoInstrutor
     */
    public MontarTreinoInstrutor() {
        initComponents();
    }

    private Instrutor instrutorLogado;
    private Aluno alunoSelecionado;

    public MontarTreinoInstrutor(Instrutor instrutorLogado, Aluno alunoSelecionado) {
        this.instrutorLogado = instrutorLogado;
        this.alunoSelecionado = alunoSelecionado;
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelExercicio1 = new javax.swing.JLabel();
        cxPeso1 = new javax.swing.JTextField();
        labelNome = new javax.swing.JLabel();
        cxExercicio1 = new javax.swing.JTextField();
        labelExercicio2 = new javax.swing.JLabel();
        cxRepeticoes1 = new javax.swing.JTextField();
        labelExercicio3 = new javax.swing.JLabel();
        cxPeso2 = new javax.swing.JTextField();
        labelNome1 = new javax.swing.JLabel();
        cxExercicio2 = new javax.swing.JTextField();
        labelExercicio4 = new javax.swing.JLabel();
        cxRepeticoes2 = new javax.swing.JTextField();
        cxExercicio3 = new javax.swing.JTextField();
        labelExercicio5 = new javax.swing.JLabel();
        cxRepeticoes3 = new javax.swing.JTextField();
        labelExercicio6 = new javax.swing.JLabel();
        cxPeso3 = new javax.swing.JTextField();
        labelNome2 = new javax.swing.JLabel();
        cxExercicio4 = new javax.swing.JTextField();
        labelExercicio7 = new javax.swing.JLabel();
        cxRepeticoes4 = new javax.swing.JTextField();
        labelExercicio8 = new javax.swing.JLabel();
        cxPeso4 = new javax.swing.JTextField();
        labelNome3 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        menuInstrutor = new javax.swing.JMenuBar();
        menuMontarIA = new javax.swing.JMenu();
        itemMontarIA = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelExercicio1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio1.setText("Peso 1:");

        cxPeso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPeso1ActionPerformed(evt);
            }
        });

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Exercício 1:");

        cxExercicio1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxExercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxExercicio1ActionPerformed(evt);
            }
        });

        labelExercicio2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio2.setText("Repetições 1:");

        cxRepeticoes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRepeticoes1ActionPerformed(evt);
            }
        });

        labelExercicio3.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio3.setText("Peso 2:");

        cxPeso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPeso2ActionPerformed(evt);
            }
        });

        labelNome1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome1.setText("Exercício 2:");

        cxExercicio2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxExercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxExercicio2ActionPerformed(evt);
            }
        });

        labelExercicio4.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio4.setText("Repetições 2:");

        cxRepeticoes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRepeticoes2ActionPerformed(evt);
            }
        });

        cxExercicio3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxExercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxExercicio3ActionPerformed(evt);
            }
        });

        labelExercicio5.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio5.setText("Repetições 3:");

        cxRepeticoes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRepeticoes3ActionPerformed(evt);
            }
        });

        labelExercicio6.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio6.setText("Peso 3:");

        cxPeso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPeso3ActionPerformed(evt);
            }
        });

        labelNome2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome2.setText("Exercício 3:");

        cxExercicio4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxExercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxExercicio4ActionPerformed(evt);
            }
        });

        labelExercicio7.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio7.setText("Repetições 4:");

        cxRepeticoes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxRepeticoes4ActionPerformed(evt);
            }
        });

        labelExercicio8.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelExercicio8.setText("Peso 4:");

        cxPeso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxPeso4ActionPerformed(evt);
            }
        });

        labelNome3.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome3.setText("Exercício 4:");

        btnSalvar.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 255, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        menuMontarIA.setText("Montar com IA");
        menuMontarIA.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemMontarIA.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemMontarIA.setText("Montar com IA");
        itemMontarIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMontarIAActionPerformed(evt);
            }
        });
        menuMontarIA.add(itemMontarIA);

        menuInstrutor.add(menuMontarIA);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuInstrutor.add(div1);

        menuSair.setBackground(new java.awt.Color(255, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 0, 0));
        menuSair.setText("Voltar");
        menuSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Voltar");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuInstrutor.add(menuSair);

        setJMenuBar(menuInstrutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalvar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxRepeticoes4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPeso4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxExercicio4, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxRepeticoes3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPeso3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxExercicio3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxRepeticoes2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPeso2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxExercicio2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxRepeticoes1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelExercicio1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxPeso1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cxExercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxExercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio1)
                    .addComponent(cxPeso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio2)
                    .addComponent(cxRepeticoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome1)
                    .addComponent(cxExercicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio3)
                    .addComponent(cxPeso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio4)
                    .addComponent(cxRepeticoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome2)
                    .addComponent(cxExercicio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio6)
                    .addComponent(cxPeso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio5)
                    .addComponent(cxRepeticoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome3)
                    .addComponent(cxExercicio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio8)
                    .addComponent(cxPeso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelExercicio7)
                    .addComponent(cxRepeticoes4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnSalvar)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMontarIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMontarIAActionPerformed
    try {
        // pegar os dados do diálogo
        TreinoParametrosDialog dlg = new TreinoParametrosDialog(this);
        dlg.setVisible(true);
        if (!dlg.isConfirmado()) return;

        var r = dlg.getResult();

        // cria o gerador
        var client = new OpenRouterClient(System.getenv("OPENROUTER_API_KEY"));
        var gerador = new GeradorTreinoIA(client);

        // gera os exercícios
        var dados = gerador.gerarTreino(
            r.getGrupo(),
            r.getPeso(),
            r.getObjetivo(),
            r.getIdade()
        );

        // mostra na tela
        // Exercício 1
        cxExercicio1.setText(dados.getOrDefault("Exercício1", ""));
        cxPeso1.setText(dados.getOrDefault("Peso1", ""));
        cxRepeticoes1.setText(dados.getOrDefault("Repetições1", ""));

        // Exercício 2
        cxExercicio2.setText(dados.getOrDefault("Exercício2", ""));
        cxPeso2.setText(dados.getOrDefault("Peso2", ""));
        cxRepeticoes2.setText(dados.getOrDefault("Repetições2", ""));

        // Exercício 3
        cxExercicio3.setText(dados.getOrDefault("Exercício3", ""));
        cxPeso3.setText(dados.getOrDefault("Peso3", ""));
        cxRepeticoes3.setText(dados.getOrDefault("Repetições3", ""));

        // Exercício 4
        cxExercicio4.setText(dados.getOrDefault("Exercício4", ""));
        cxPeso4.setText(dados.getOrDefault("Peso4", ""));
        cxRepeticoes4.setText(dados.getOrDefault("Repetições4", ""));


        javax.swing.JOptionPane.showMessageDialog(this, "Treino gerado!\nRevise e altere antes de salvar!", "IA", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao gerar treino: " + e.getMessage(), "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_itemMontarIAActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // cria um objeto da tela
        AlunosInstrutor telaLogin = new AlunosInstrutor(instrutorLogado, alunoSelecionado);

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void cxPeso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPeso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPeso1ActionPerformed

    private void cxExercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxExercicio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxExercicio1ActionPerformed

    private void cxRepeticoes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRepeticoes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRepeticoes1ActionPerformed

    private void cxPeso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPeso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPeso2ActionPerformed

    private void cxExercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxExercicio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxExercicio2ActionPerformed

    private void cxRepeticoes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRepeticoes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRepeticoes2ActionPerformed

    private void cxExercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxExercicio3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxExercicio3ActionPerformed

    private void cxRepeticoes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRepeticoes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRepeticoes3ActionPerformed

    private void cxPeso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPeso3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPeso3ActionPerformed

    private void cxExercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxExercicio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxExercicio4ActionPerformed

    private void cxRepeticoes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxRepeticoes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxRepeticoes4ActionPerformed

    private void cxPeso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxPeso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxPeso4ActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // 1) Validação rápida
            if (alunoSelecionado == null) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Nenhum aluno selecionado para vincular o treino.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            Control.BD.ExercicioDAO dao = new Control.BD.ExercicioDAO();
            dao.criarTabela();

            // 2) Gera um novo ID de treino
            int novoTreinoId = dao.gerarNovoTreinoId();

            // 3) Monta a lista de exercícios
            java.util.List<Model.Exercicio> lista = java.util.Arrays.asList(
                new Model.Exercicio(
                    cxExercicio1.getText().trim(),
                    cxPeso1.getText().trim(),
                    cxRepeticoes1.getText().trim()
                ),
                new Model.Exercicio(
                    cxExercicio2.getText().trim(),
                    cxPeso2.getText().trim(),
                    cxRepeticoes2.getText().trim()
                ),
                new Model.Exercicio(
                    cxExercicio3.getText().trim(),
                    cxPeso3.getText().trim(),
                    cxRepeticoes3.getText().trim()
                ),
                new Model.Exercicio(
                    cxExercicio4.getText().trim(),
                    cxPeso4.getText().trim(),
                    cxRepeticoes4.getText().trim()
                )
            );

            // 4) Salva exercícios com o mesmo treino_id
            dao.salvar(lista, novoTreinoId);

            // 5) Atualiza o alunoSelecionado com esse treino_id
            try (java.sql.Connection con = Control.BD.ConexaoBD.conectar();
                 java.sql.PreparedStatement ps = con.prepareStatement(
                     "UPDATE aluno SET treino_id = ? WHERE id_aluno = ?"
                 )) {

                ps.setInt(1, novoTreinoId);
                ps.setInt(2, alunoSelecionado.getIdAluno());
                ps.executeUpdate();
            }

            // Atualiza o objeto em memória também
            alunoSelecionado.setTreinoId(novoTreinoId);

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Treino salvo com sucesso!\nID do treino: " + novoTreinoId,
                "Banco de dados",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao salvar treino: " + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MontarTreinoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MontarTreinoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MontarTreinoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MontarTreinoInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MontarTreinoInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cxExercicio1;
    private javax.swing.JTextField cxExercicio2;
    private javax.swing.JTextField cxExercicio3;
    private javax.swing.JTextField cxExercicio4;
    private javax.swing.JTextField cxPeso1;
    private javax.swing.JTextField cxPeso2;
    private javax.swing.JTextField cxPeso3;
    private javax.swing.JTextField cxPeso4;
    private javax.swing.JTextField cxRepeticoes1;
    private javax.swing.JTextField cxRepeticoes2;
    private javax.swing.JTextField cxRepeticoes3;
    private javax.swing.JTextField cxRepeticoes4;
    private javax.swing.JMenu div1;
    private javax.swing.JMenuItem itemMontarIA;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JLabel labelExercicio1;
    private javax.swing.JLabel labelExercicio2;
    private javax.swing.JLabel labelExercicio3;
    private javax.swing.JLabel labelExercicio4;
    private javax.swing.JLabel labelExercicio5;
    private javax.swing.JLabel labelExercicio6;
    private javax.swing.JLabel labelExercicio7;
    private javax.swing.JLabel labelExercicio8;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelNome2;
    private javax.swing.JLabel labelNome3;
    private javax.swing.JMenuBar menuInstrutor;
    private javax.swing.JMenu menuMontarIA;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
