/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Instrutor;

import Model.Instrutor;
import View.Instrutor.LoginInstrutor;

/**
 *
 * @author T-GAMER
 */
public class TelaInstrutor extends javax.swing.JFrame {

    private Instrutor instrutorLogado;

    public TelaInstrutor() {
        this(null); // opcional, pro NetBeans
    }

    public TelaInstrutor(Instrutor instrutorLogado) {
        this.instrutorLogado = instrutorLogado;
        initComponents();

        if (this.instrutorLogado != null) {
            // exemplo: mostrar nome do instrutor em um label na tela
            cxNome.setText(instrutorLogado.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        labelAcademia = new javax.swing.JLabel();
        cxNomeAcademia = new javax.swing.JTextField();
        menuInstrutor = new javax.swing.JMenuBar();
        menuAlunos = new javax.swing.JMenu();
        itemVerAlunos = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Instrutor:");

        cxNome.setEditable(false);
        cxNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelAcademia.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelAcademia.setText("Academia:");

        cxNomeAcademia.setEditable(false);
        cxNomeAcademia.setText("GymFlow");
        cxNomeAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeAcademiaActionPerformed(evt);
            }
        });

        menuAlunos.setText("Ver alunos");
        menuAlunos.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemVerAlunos.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemVerAlunos.setText("Ver alunos");
        itemVerAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVerAlunosActionPerformed(evt);
            }
        });
        menuAlunos.add(itemVerAlunos);

        menuInstrutor.add(menuAlunos);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuInstrutor.add(div1);

        menuSair.setBackground(new java.awt.Color(255, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 0, 0));
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuInstrutor.add(menuSair);

        setJMenuBar(menuInstrutor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAcademia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNomeAcademia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcademia)
                    .addComponent(cxNomeAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxNomeAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeAcademiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeAcademiaActionPerformed

    private void itemVerAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVerAlunosActionPerformed
        VerAlunosInstrutor tela = new VerAlunosInstrutor(instrutorLogado);
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itemVerAlunosActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // cria um objeto da tela
        LoginInstrutor telaLogin = new LoginInstrutor();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNomeAcademia;
    private javax.swing.JMenu div1;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemVerAlunos;
    private javax.swing.JLabel labelAcademia;
    private javax.swing.JLabel labelNome;
    private javax.swing.JMenu menuAlunos;
    private javax.swing.JMenuBar menuInstrutor;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
