/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Instrutor;

import Control.BD.ConexaoBD;
import Model.Instrutor;
import Model.Aluno;
import View.Instrutor.TelaInstrutor;
import View.Instrutor.AlunosInstrutor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author T-GAMER
 */
public class VerAlunosInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form VerAlunosInstrutor
     */
    public VerAlunosInstrutor() {
        initComponents();
    }
    
    private Instrutor instrutorLogado;
    private final Aluno[] slots = new Aluno[4];
    
    public VerAlunosInstrutor(Instrutor instrutorLogado) {
        this.instrutorLogado = instrutorLogado;
        initComponents();

        if (instrutorLogado != null) {
            setTitle("Alunos de " + instrutorLogado.getNome());
        }

        carregarAlunosDoInstrutor();
    }
    
    private void carregarAlunosDoInstrutor() {
        if (instrutorLogado == null || instrutorLogado.getIdInstrutor() == null) return;

        // zera os slots antes de carregar
        java.util.Arrays.fill(slots, null);

        try (Connection con = ConexaoBD.conectar();
             PreparedStatement ps = con.prepareStatement(
                 "SELECT id_aluno, cpf, nome, usuario, senha, treino_id, instrutor_id " +
                 "FROM aluno WHERE instrutor_id = ? ORDER BY id_aluno LIMIT 4"
             )) {

            ps.setInt(1, instrutorLogado.getIdInstrutor());

            try (ResultSet rs = ps.executeQuery()) {
                int i = 0;
                while (rs.next() && i < 4) {
                    Aluno a = new Aluno();
                    a.setIdAluno(rs.getInt("id_aluno"));
                    a.setCpf(rs.getString("cpf"));
                    a.setNome(rs.getString("nome"));
                    a.setUsuario(rs.getString("usuario"));
                    a.setSenha(rs.getString("senha"));

                    Object t  = rs.getObject("treino_id");
                    Object id = rs.getObject("instrutor_id");
                    if (t  != null) a.setTreinoId((Integer) t);
                    if (id != null) a.setInstrutorId((Integer) id);

                    slots[i] = a;
                    i++;
                }
            }

            atualizarTextoEBotoes();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Erro ao carregar alunos do instrutor:\n" + e.getMessage(),
                    "Erro",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }


    private void atualizarTextoEBotoes() {
        javax.swing.JButton[] botoes = { btnAluno1, btnAluno2, btnAluno3, btnAluno4 };

        for (int i = 0; i < botoes.length; i++) {
            if (slots[i] != null) {
                botoes[i].setText(slots[i].getNome());
                botoes[i].setEnabled(true);
            } else {
                botoes[i].setText("— Vazio —");
                botoes[i].setEnabled(false);  // não clica, não abre nada
            }
        }
    }
    
    private void abrirSlot(int idx) {
        Aluno a = slots[idx];
        if (a == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Nenhum aluno cadastrado neste slot.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // abre a tela de aluno do instrutor já com o aluno certo
        AlunosInstrutor telaAluno = new AlunosInstrutor(instrutorLogado, a);
        telaAluno.setVisible(true);
        this.dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAluno1 = new javax.swing.JButton();
        btnAluno2 = new javax.swing.JButton();
        btnAluno3 = new javax.swing.JButton();
        btnAluno4 = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAluno1.setBackground(new java.awt.Color(102, 102, 102));
        btnAluno1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAluno1.setForeground(new java.awt.Color(255, 255, 255));
        btnAluno1.setText("Aluno 1");
        btnAluno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluno1ActionPerformed(evt);
            }
        });

        btnAluno2.setBackground(new java.awt.Color(102, 102, 102));
        btnAluno2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAluno2.setForeground(new java.awt.Color(255, 255, 255));
        btnAluno2.setText("Aluno 3");
        btnAluno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluno2ActionPerformed(evt);
            }
        });

        btnAluno3.setBackground(new java.awt.Color(102, 102, 102));
        btnAluno3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAluno3.setForeground(new java.awt.Color(255, 255, 255));
        btnAluno3.setText("Aluno 2");
        btnAluno3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluno3ActionPerformed(evt);
            }
        });

        btnAluno4.setBackground(new java.awt.Color(102, 102, 102));
        btnAluno4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAluno4.setForeground(new java.awt.Color(255, 255, 255));
        btnAluno4.setText("Aluno 4");
        btnAluno4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAluno4ActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 0, 0));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAluno2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAluno4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAluno1)
                                .addGap(131, 131, 131)
                                .addComponent(btnAluno3)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAluno3)
                    .addComponent(btnAluno1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAluno2)
                    .addComponent(btnAluno4))
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        TelaInstrutor telaLogin = new TelaInstrutor(instrutorLogado);
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnAluno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluno1ActionPerformed
        abrirSlot(0);
    }//GEN-LAST:event_btnAluno1ActionPerformed

    private void btnAluno3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluno3ActionPerformed
        abrirSlot(1);
    }//GEN-LAST:event_btnAluno3ActionPerformed

    private void btnAluno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluno2ActionPerformed
        abrirSlot(2);
    }//GEN-LAST:event_btnAluno2ActionPerformed

    private void btnAluno4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAluno4ActionPerformed
        abrirSlot(3);
    }//GEN-LAST:event_btnAluno4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerAlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerAlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerAlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerAlunosInstrutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerAlunosInstrutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAluno1;
    private javax.swing.JButton btnAluno2;
    private javax.swing.JButton btnAluno3;
    private javax.swing.JButton btnAluno4;
    private javax.swing.JButton btnVoltar;
    // End of variables declaration//GEN-END:variables
}
