/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Admin;

import Control.CRUDAluno.ConsultarAluno;
import Control.CRUDAluno.CriarAluno;
import Model.Aluno;
import View.Admin.TelaAdmin;
import View.AlunoDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author T-GAMER
 */
public class EditarAlunosAdmin extends javax.swing.JFrame {

    /**
     * Creates new form EditarAlunosAdmin
     */
    public EditarAlunosAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCPF = new javax.swing.JLabel();
        cxCPF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menuAdmin = new javax.swing.JMenuBar();
        menuConsultar = new javax.swing.JMenu();
        itemConsultar = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuEditar = new javax.swing.JMenu();
        itemEditar = new javax.swing.JMenuItem();
        div2 = new javax.swing.JMenu();
        menuExcluir = new javax.swing.JMenu();
        itemExcluir = new javax.swing.JMenuItem();
        div3 = new javax.swing.JMenu();
        menuAdicionar = new javax.swing.JMenu();
        itemAdicionar = new javax.swing.JMenuItem();
        itemAdicionarInstrutores2 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCPF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCPF.setText("CPF:");

        jLabel1.setText("Use o campo CPF para as funções de consultar, editar e excluir alunos.");

        menuConsultar.setText("Consultar aluno");
        menuConsultar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemConsultar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemConsultar.setText("Consultar aluno");
        itemConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarActionPerformed(evt);
            }
        });
        menuConsultar.add(itemConsultar);

        menuAdmin.add(menuConsultar);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAdmin.add(div1);

        menuEditar.setText("Editar aluno");
        menuEditar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemEditar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemEditar.setText("Editar aluno");
        itemEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarActionPerformed(evt);
            }
        });
        menuEditar.add(itemEditar);

        menuAdmin.add(menuEditar);

        div2.setText("|");
        div2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAdmin.add(div2);

        menuExcluir.setText("Excluir alunos");
        menuExcluir.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemExcluir.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemExcluir.setText("Excluir alunos");
        itemExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExcluirActionPerformed(evt);
            }
        });
        menuExcluir.add(itemExcluir);

        menuAdmin.add(menuExcluir);

        div3.setText("|");
        div3.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAdmin.add(div3);

        menuAdicionar.setText("Adicionar alunos");
        menuAdicionar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemAdicionar.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemAdicionar.setText("Adicionar alunos");
        itemAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAdicionarActionPerformed(evt);
            }
        });
        menuAdicionar.add(itemAdicionar);

        menuAdmin.add(menuAdicionar);

        itemAdicionarInstrutores2.setText("|");
        itemAdicionarInstrutores2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAdmin.add(itemAdicionarInstrutores2);

        menuSair.setBackground(new java.awt.Color(255, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 0, 0));
        menuSair.setText("Voltar");
        menuSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Voltar");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuAdmin.add(menuSair);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCPF)
                        .addGap(18, 18, 18)
                        .addComponent(cxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCPF)
                    .addComponent(cxCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarActionPerformed
        try {
            String cpf = cxCPF.getText().trim();   // só usa o CPF mesmo

            if (cpf.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Informe o CPF do aluno para consultar.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            ConsultarAluno consulta = new ConsultarAluno();
            Aluno aluno = consulta.buscarPorCpf(cpf);

            if (aluno == null) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Aluno não encontrado.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // abre a janelinha SOMENTE LEITURA
            AlunoDialog dialog = new AlunoDialog(this, aluno, true);
            dialog.setVisible(true);
            // não chama getAluno(), não salva nada – é só visualização

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao consultar aluno:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_itemConsultarActionPerformed

    private void itemEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarActionPerformed
        try {
            String cpf = cxCPF.getText().trim(); // JTextField CPF da tela principal

            if (cpf.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Informe o CPF do aluno que deseja editar.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // 1) busca aluno no banco
            ConsultarAluno consulta = new ConsultarAluno();
            Aluno existente = consulta.buscarPorCpf(cpf);

            if (existente == null) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Aluno não encontrado.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // 2) abre dialog já preenchido
            AlunoDialog dialog = new AlunoDialog(this, existente); // edição
            dialog.setVisible(true);
            if (!dialog.isConfirmado()) return;
            Aluno atualizado = dialog.getAluno();
            // garante que o CPF não foi mudado
            atualizado.setCpf(existente.getCpf());

            // 4) salva no banco
            new Control.CRUDAluno.EditarAluno().executar(atualizado);

            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Aluno atualizado com sucesso!",
                "Sucesso",
                javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao editar aluno:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_itemEditarActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // cria um objeto da tela
        TelaAdmin telaLogin = new TelaAdmin();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    private void itemAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAdicionarActionPerformed
        try {
            AlunoDialog dialog = new AlunoDialog(this);
            
            dialog.setVisible(true);
            if (!dialog.isConfirmado()) return;
            
            Aluno novo = dialog.getAluno();
                        
            new CriarAluno().executar(novo);

            JOptionPane.showMessageDialog(this, "Aluno adicionado com sucesso!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Erro ao adicionar aluno:\n" + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemAdicionarActionPerformed

    private void itemExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExcluirActionPerformed
        try {
            String cpf = cxCPF.getText().trim();  // campo CPF da tela

            if (cpf.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Informe o CPF do aluno que deseja excluir.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            int op = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Tem certeza que deseja excluir o aluno com CPF " + cpf + "?",
                "Confirmar exclusão",
                javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (op != javax.swing.JOptionPane.YES_OPTION) {
                return; // usuário desistiu
            }

            Control.CRUDAluno.ApagarAluno apagar = new Control.CRUDAluno.ApagarAluno();
            int apagados = apagar.porCpf(cpf);

            if (apagados == 0) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Nenhum aluno encontrado com esse CPF.",
                    "Aviso",
                    javax.swing.JOptionPane.WARNING_MESSAGE
                );
            } else {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Aluno excluído com sucesso!",
                    "Sucesso",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                );

                // limpa e destrava os campos
                cxCPF.setText("");
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Erro ao excluir aluno:\n" + e.getMessage(),
                "Erro",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_itemExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAlunosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAlunosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAlunosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAlunosAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarAlunosAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxCPF;
    private javax.swing.JMenu div1;
    private javax.swing.JMenu div2;
    private javax.swing.JMenu div3;
    private javax.swing.JMenuItem itemAdicionar;
    private javax.swing.JMenu itemAdicionarInstrutores2;
    private javax.swing.JMenuItem itemConsultar;
    private javax.swing.JMenuItem itemEditar;
    private javax.swing.JMenuItem itemExcluir;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JMenu menuAdicionar;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenu menuEditar;
    private javax.swing.JMenu menuExcluir;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
