/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Admin;

import View.Admin.LoginAdmin;

/**
 *
 * @author T-GAMER
 */
public class TelaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNome = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        labelAcademia = new javax.swing.JLabel();
        cxNomeAcademia = new javax.swing.JTextField();
        menuAdmin = new javax.swing.JMenuBar();
        menuAlunos = new javax.swing.JMenu();
        itemEditarAlunos = new javax.swing.JMenuItem();
        div1 = new javax.swing.JMenu();
        menuInstrutores = new javax.swing.JMenu();
        itemEditarInstrutores = new javax.swing.JMenuItem();
        div2 = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenu();
        itemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNome.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelNome.setText("Administrador:");

        cxNome.setEditable(false);
        cxNome.setText("SuperUser");
        cxNome.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeActionPerformed(evt);
            }
        });

        labelAcademia.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        labelAcademia.setText("Academia:");

        cxNomeAcademia.setEditable(false);
        cxNomeAcademia.setText("GymFlow");
        cxNomeAcademia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxNomeAcademiaActionPerformed(evt);
            }
        });

        menuAlunos.setText("Editar alunos");
        menuAlunos.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemEditarAlunos.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemEditarAlunos.setText("Editar alunos");
        itemEditarAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarAlunosActionPerformed(evt);
            }
        });
        menuAlunos.add(itemEditarAlunos);

        menuAdmin.add(menuAlunos);

        div1.setText("|");
        div1.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAdmin.add(div1);

        menuInstrutores.setText("Editar instrutores");
        menuInstrutores.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemEditarInstrutores.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 12)); // NOI18N
        itemEditarInstrutores.setText("Editar instrutores");
        itemEditarInstrutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarInstrutoresActionPerformed(evt);
            }
        });
        menuInstrutores.add(itemEditarInstrutores);

        menuAdmin.add(menuInstrutores);

        div2.setText("|");
        div2.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N
        menuAdmin.add(div2);

        menuSair.setBackground(new java.awt.Color(255, 0, 0));
        menuSair.setForeground(new java.awt.Color(255, 0, 0));
        menuSair.setText("Sair");
        menuSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 1, 14)); // NOI18N

        itemSair.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 12)); // NOI18N
        itemSair.setForeground(new java.awt.Color(255, 0, 0));
        itemSair.setText("Sair");
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuSair.add(itemSair);

        menuAdmin.add(menuSair);

        setJMenuBar(menuAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelAcademia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNomeAcademia))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAcademia)
                    .addComponent(cxNomeAcademia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeActionPerformed

    private void cxNomeAcademiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeAcademiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeAcademiaActionPerformed

    private void itemEditarAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarAlunosActionPerformed
        // cria um objeto da tela
        EditarAlunosAdmin telaLogin = new EditarAlunosAdmin();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_itemEditarAlunosActionPerformed

    private void itemEditarInstrutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarInstrutoresActionPerformed
        // cria um objeto da tela
        EditarInstrutoresAdmin telaLogin = new EditarInstrutoresAdmin();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_itemEditarInstrutoresActionPerformed

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        // cria um objeto da tela
        LoginAdmin telaLogin = new LoginAdmin();

        // exibe
        telaLogin.setVisible(true);

        // fecha a tela atual
        this.dispose();
    }//GEN-LAST:event_itemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNomeAcademia;
    private javax.swing.JMenu div1;
    private javax.swing.JMenu div2;
    private javax.swing.JMenuItem itemEditarAlunos;
    private javax.swing.JMenuItem itemEditarInstrutores;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JLabel labelAcademia;
    private javax.swing.JLabel labelNome;
    private javax.swing.JMenuBar menuAdmin;
    private javax.swing.JMenu menuAlunos;
    private javax.swing.JMenu menuInstrutores;
    private javax.swing.JMenu menuSair;
    // End of variables declaration//GEN-END:variables
}
